### PR TITLE
Sort tags alphabetically

### PR DESCRIPTION
**Pull request by CapsParrot**
Sort all the tags alphabetically

### CODE REVIEW

**Comment by Doridian** [comment]
Should be implemented via https://github.com/Doridian/factorio-fox-todo/commit/79c46fc082695b3ebfbd138e79653bf153f632a2 which avoids some intermediate tables.

Thanks for the PR :)

**Comment by CapsParrot** [comment]
Nice and probably a lot better then what I had made, I don't know I normally don't program in lua.

There is a reason why I submitted a change and it is because I use your mode in a different way then intented 

I'm current playing Space Exploration so lots of surfaces and resources patches
I use the mod called "Resource Map Label Marker" to tag resources on the map and with your mod I could get them in an easy to look at list.
All I had to do is remove the "TODO: " from the config.lua
The sort was to get an easy to use list of tagged resources :D

There is one thing I have to be aware of because I'm using your mod wrong, the "Own" filter crash the game.
I think it is because of the way "Resource Map Label Marker" is tagging, maybe the tag doesn't have player information, I don't know, not importent 

Just thought you should know

**Comment by Doridian** [comment]
Oh no! I added https://github.com/Doridian/factorio-fox-todo/issues/13 to see if I can track this down

**Comment by Doridian** [comment]
@CapsParrot If you have any error messages or the like, feel free to add them to the issue, makes it easier for me to check

**Pull request closed without merging**
